base_model: "openai/whisper-large-v3"
new_model_name: "Phil-Ear-N1"
hf_username: "phil-ai"
dataset_name: "mozilla-foundation/common_voice_16_1" # Hoặc dataset youtube tự tạo
dataset_subset: "vi"
language: "Vietnamese"

steps: 500
batch_size: 8
grad_accum: 2
learning_rate: 1.0e-5